/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhasCategoriasRouteImport } from './routes/minhas-categorias'
import { Route as HotDealsRouteImport } from './routes/hot-deals'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as IndexRouteImport } from './routes/index'

const MinhasCategoriasRoute = MinhasCategoriasRouteImport.update({
  id: '/minhas-categorias',
  path: '/minhas-categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const HotDealsRoute = HotDealsRouteImport.update({
  id: '/hot-deals',
  path: '/hot-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/hot-deals': typeof HotDealsRoute
  '/minhas-categorias': typeof MinhasCategoriasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/hot-deals': typeof HotDealsRoute
  '/minhas-categorias': typeof MinhasCategoriasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/hot-deals': typeof HotDealsRoute
  '/minhas-categorias': typeof MinhasCategoriasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastrar' | '/hot-deals' | '/minhas-categorias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastrar' | '/hot-deals' | '/minhas-categorias'
  id: '__root__' | '/' | '/cadastrar' | '/hot-deals' | '/minhas-categorias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRoute: typeof CadastrarRoute
  HotDealsRoute: typeof HotDealsRoute
  MinhasCategoriasRoute: typeof MinhasCategoriasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minhas-categorias': {
      id: '/minhas-categorias'
      path: '/minhas-categorias'
      fullPath: '/minhas-categorias'
      preLoaderRoute: typeof MinhasCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-deals': {
      id: '/hot-deals'
      path: '/hot-deals'
      fullPath: '/hot-deals'
      preLoaderRoute: typeof HotDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRoute: CadastrarRoute,
  HotDealsRoute: HotDealsRoute,
  MinhasCategoriasRoute: MinhasCategoriasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
